# Generated by Django 6.0.5 on 2026-05-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('role', models.CharField(max_length=150, verbose_name='Роль / Профессия')),
                ('bio', models.TextField(verbose_name='О себе')),
                ('skills', models.CharField(help_text='Через запятую: Python, Django', max_length=255, verbose_name='Навыки')),
                ('github', models.URLField(blank=True, verbose_name='Ссылка на GitHub')),
                ('telegram', models.URLField(blank=True, verbose_name='Ссылка на Telegram')),
            ],
            options={
                'verbose_name': 'Мой профиль',
                'verbose_name_plural': 'Мой профиль',
            },
        ),
    ]
